api_platform:
  title: Coach Booker API
  version: 1.0.0

  eager_loading:
    force_eager: false

  formats:
    json: ['application/json']
    jsonld: ['application/json+ld']
    html: ['text/html']
    multipart: ['multipart/form-data']

  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']

  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
      standard_put: true

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
