const ORGANIZATION_USER_ROLES = {
	ROLE_ORG_ADMIN: 'ROLE_ORG_ADMIN',
	ROLE_ORG_COACH: 'ROLE_ORG_COACH',
};

const USER_ROLES = {
	ROLE_ADMIN: 'ROLE_ADMIN',
	ROLE_CLIENT: 'ROLE_CLIENT',
	...ORGANIZATION_USER_ROLES,
};

const USER_STATUSES = {
	ACTIVE: 'ACTIVE',
	INACTIVE: 'INACTIVE',
	REJECTED: 'REJECTED',
	DELETED: 'DELETED',
};

export { ORGANIZATION_USER_ROLES, USER_ROLES, USER_STATUSES };
