name: Deploy Backend to Heroku

on:
  push:
    branches:
      - 'backcd' # Changer apres tests
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Heroku Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku login --api-key $HEROKU_API_KEY

      - name: Add Heroku remote
        run: |
          heroku git:remote -a coachbookerbackend

      - name: Deploy to Heroku
        run: |
          git push heroku ${GITHUB_REF#refs/heads/}:master

      - name: Verify Deployment
        run: |
          heroku ps --app coachbookerbackend
